language: java
dist: trusty
jdk: oraclejdk8

script:
  - ./gradlew clean jar

after_script:
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print "$3" "$4" "$5"}'
