language: java
dist: trusty
jdk: oraclejdk8

script:
  - ./gradlew clean jar
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print "$3" "$4" "$5"}'
  - ./gradlew test jacocoTestCoverageVerification

after_script:
  - ./gradlew test

deploy:
  provider: script
  script: bash scripts/deploy.sh
  # on:
  #   branch: master
