language: java
dist: trusty
jdk: oraclejdk8

env:
  - COVERAGE=0.3 SUBPROJECT=ui
  - COVERAGE=0.3 SUBPROJECT=service/cart
  - COVERAGE=0.3 SUBPROJECT=service/user
  - COVERAGE=0.3 SUBPROJECT=repository/order
  - COVERAGE=0.3 SUBPROJECT=repository/cart
  - COVERAGE=0.3 SUBPROJECT=repository/product
  - COVERAGE=0.3 SUBPROJECT=repository/user

jobs:
  include:
    - stage: script
      script: ./gradlew clean jar
      env: SUBPROJECT=ui
    - script: find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print "$3" "$4" "$5"}'
      env: SUBPROJECT=ui
    - stage: after_script
      script: COVERAGE={$COVERAGE} ./gradlew -p ./monolithic/${SUBPROJECT} check
    - stage: deploy
      env: SUBPROJECT=ui
      provider: script
      script: bash scripts/deploy.sh
