language: java
dist: trusty
jdk: oraclejdk8

env:
  - COVERAGE=1.0 SUBPROJECT=ui
  - COVERAGE=1.0 SUBPROJECT=service/cart
  - COVERAGE=1.0 SUBPROJECT=service/user
  - COVERAGE=1.0 SUBPROJECT=repository/order
  - COVERAGE=1.0 SUBPROJECT=repository/cart
  - COVERAGE=1.0 SUBPROJECT=repository/product
  - COVERAGE=1.0 SUBPROJECT=repository/user

script:
  - ./gradlew clean jar
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print "$3" "$4" "$5"}'

jobs:
  include:
    - stage: test
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/${SUBPROJECT} check

deploy:
  provider: script
  script: bash scripts/deploy.sh
  if: type NOT IN (push, pull_request)
