language: java
dist: trusty
jdk: oraclejdk8

env:
  COVERAGE=0.3

script:
  - ./gradlew clean jar
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print "$3" "$4" "$5"}'
  # jobs:
  #   include:
  #     - stage: script
  #       script: COVERAGE=0.5 ./gradlew -p ./monolithic/ui check
  #     - script: COVERAGE=0.5 ./gradlew -p ./monolithic/service/cart check
  #     - script: COVERAGE=0.5 ./gradlew -p ./monolithic/service/user check
  #     - script: COVERAGE=0.5 ./gradlew -p ./monolithic/repository/order check
  #     - script: COVERAGE=0.5 ./gradlew -p ./monolithic/repository/cart check
  #     - script: COVERAGE=0.5 ./gradlew -p ./monolithic/repository/product check
  #     - script: COVERAGE=0.5 ./gradlew -p ./monolithic/repository/user check

deploy:
  provider: script
  script: bash scripts/deploy.sh
