language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

env:
  - TARGET=ui COVERAGE=0.25
  - TARGET=service/card COVERAGE=0.25
  - TARGET=service/user COVERAGE=0.25
  - TARGET=repository/order COVERAGE=0.25
  - TARGET=repository/cart COVERAGE=0.25
  - TARGET=repository/product COVERAGE=0.25
  - TARGET=repository/user COVERAGE=0.25

jobs:
  include:
    - stage: build
      script: ./gradlew clean jar
    - stage: deploy
      install: skip
      before_deploy:
        - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check
      deploy:
        provider: script
        script:
          - script: echo 'WIP'